[unstable]
build-std = ["core"]

[build]
target = ".cargo/avr-atmega32u4.json"

[target.'cfg(target_arch = "avr")']
runner = "ravedude leonardo"

# Configure the build for minimal size - AVRs have very little program memory
[profile.dev]
panic = "abort"
lto = true
opt-level = "s"

[profile.release]
panic = "abort"
codegen-units = 1
lto = true
opt-level = "s"
strip = "symbols"
