[unstable]
build-std = ["core"]

[build]
target = "avr-none"
rustflags = ["-C", "target-cpu=atmega32u4"]

[target.'cfg(target_arch = "avr")']
runner = "ravedude leonardo -P /dev/ttyACM0 -d 0"

# Configure the build for minimal size - AVRs have very little program memory
[profile.dev]
panic = "abort"
lto = true
opt-level = "s"

[profile.release]
panic = "abort"
codegen-units = 1
lto = true
opt-level = "s"
strip = "symbols"
